# 1. Usar imagen base de Ubuntu
FROM ubuntu:latest

# 2. Actualizar el sistema e instalar las herramientas de red AMQP
RUN apt-get update && apt-get install -y amqp-tools

# 3. Iniciar con una terminal interactiva
CMD ["/bin/bash"]