# --- rabbitmq.conf ---

# 1. Crear el usuario virtual para el servidor AMQP (en vez de usar 'guest')
default_user = admin
default_pass = 1234

# 2. Crear un Virtual Host (el entorno aislado donde vivirán tus colas)
default_vhost = entorno_amqp

# 3. Asignar etiquetas de administrador a tu nuevo usuario para que pueda 
# configurar colas y usar la interfaz web sin restricciones.
management.listener.port = 15672
loopback_users.guest = false